name: API PHP Slim Workflow
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: API build
    runs-on: ubuntu-18.04
    env:
      CONFIG_FILE: ./src/Config/config.local.php
      CONFIG_FILE_EXAMPLE: ./src/Config/config.local.php.example
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/composer
      - run: cp $CONFIG_FILE_EXAMPLE $CONFIG_FILE
      - run: sed -i 's/IP_DB/${{ secrets.MYSQL_HOST }}/' $CONFIG_FILE
      - run: sed -i 's/DB_NAME/${{ secrets.MYSQL_DATABASE }}/' $CONFIG_FILE
      - run: sed -i 's/DB_USER/${{ secrets.MYSQL_USER }}/' $CONFIG_FILE
      - run: sed -i 's/USER_PASSWORD/${{ secrets.MYSQL_PASSWORD }}/' $CONFIG_FILE
      - run: docker build . --file ./.github/actions/app/Dockerfile -t phpslim:7.2-apache
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: andrelsferreira/apiphpslim
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: ./.github/actions/app/Dockerfile
