name: Build and Publish MySQL
on:
  push:
    branches-ignore:
      - develop
      - master
jobs:
  build:
    name: Publish to Docker Repository
    runs-on: ubuntu-18.04
    env:
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/mysql
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: andrelsferreira/mysql
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs:  MYSQL_ROOT_PASSWORD, MYSQL_DATABASE, MYSQL_USER, MYSQL_PASSWORD